import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

import '../../core/theme/app_theme.dart';
import '../../core/widgets/glass.dart';
import '../../core/widgets/nebula_background.dart';

enum LegalDoc { terms, license }

class _Section {
  const _Section(this.title, this.body);
  final String title;
  final String body;
}

const _updated = 'Last updated 26 September 2026';

const _terms = [
  _Section('Agreement',
      'By playing Rockketeyes on the web or on Android you agree to these Terms of Use. If you do not agree, please do not use the app.'),
  _Section('The game',
      'Rockketeyes is a Stroop test game for entertainment and everyday brain training. It is not a medical device and does not '
          'diagnose, treat or measure any health condition. Take regular breaks and rest your eyes.'),
  _Section('Your account',
      'You can play as a guest. Connecting a Google account saves your progress and places your scores on Global Legends. You are '
          'responsible for activity on your account. You can change your nickname, avatar and country at any time.'),
  _Section('Fair play',
      'Play with your own voice or taps. Do not use bots, scripts, recordings or other tools to answer, and do not interfere with the '
          'service or other players. Nicknames must not be offensive, impersonate others or contain personal information. We may remove '
          'scores, nicknames or accounts that break these rules.'),
  _Section('Group challenges',
      'Hosts create rooms and share the PIN or QR code with the people they invite. Group results are for fun and do not count toward '
          'Global Legends. Hosts may remove players from their room.'),
  _Section('Microphone and speech',
      'During a round the app listens for color words using your device or browser speech service. Rockketeyes does not record or store '
          'your audio. See the Privacy Policy for details.'),
  _Section('Ownership',
      'Rockketeyes, its name, logo, design and software belong to Thalamuxtech. You may not copy, modify, resell or redistribute the app '
          'except as the License Policy allows.'),
  _Section('Availability',
      'We work to keep Rockketeyes running but provide it as is, without guarantees. Features, leaderboards and scores may change, be '
          'reset or become unavailable.'),
  _Section('Liability',
      'To the extent the law allows, Thalamuxtech is not liable for indirect or consequential losses arising from use of the app.'),
  _Section('Changes',
      'We may update these terms. Continuing to use Rockketeyes after an update means you accept the new terms.'),
  _Section('Contact', 'Questions: use the developer contact listed on the Rockketeyes Google Play page or at thalamux-tech.web.app.'),
];

const _license = [
  _Section('Your license to use Rockketeyes',
      'Thalamuxtech grants you a personal, non-exclusive, non-transferable, revocable license to use Rockketeyes for your own '
          'non-commercial entertainment, on the web or on devices you own or control.'),
  _Section('What is not allowed',
      'You may not sell, rent, sublicense or commercially exploit the app; copy or redistribute it; reverse engineer it except where the '
          'law permits; remove notices; or use the name and logo without permission. Hosting group challenges for friends, classes or '
          'teams is allowed; charging people to play requires written permission.'),
  _Section('Third-party components',
      'Rockketeyes includes open-source software, each used under its own license (for example BSD, MIT and Apache 2.0). The Sora and '
          'Inter fonts are used under the SIL Open Font License 1.1. Music and sound effects are CC0 public domain works. Character '
          'avatars are generated by DiceBear and remain under the licenses of their original artists. Country flags come from flagcdn.com.'),
  _Section('Your content',
      'You keep any rights you have in your nickname. You allow Rockketeyes to display your nickname, avatar, country and scores on '
          'leaderboards and in group rooms.'),
  _Section('Ending the license',
      'This license ends automatically if you break these terms. You can stop using Rockketeyes at any time.'),
];

class LegalScreen extends StatelessWidget {
  const LegalScreen({super.key, required this.doc});

  final LegalDoc doc;

  @override
  Widget build(BuildContext context) {
    final title = doc == LegalDoc.terms ? 'Terms of Use' : 'License Policy';
    final sections = doc == LegalDoc.terms ? _terms : _license;
    return Scaffold(
      body: NebulaBackground(
        intensity: 0.6,
        child: SafeArea(
          child: Center(
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 760),
              child: ListView(
                padding: const EdgeInsets.fromLTRB(16, 12, 16, 40),
                children: [
                  Row(children: [
                    GlassIconButton(
                      icon: LucideIcons.arrowLeft,
                      tooltip: 'Back',
                      onPressed: () => context.canPop() ? context.pop() : context.go('/settings'),
                    ),
                    const SizedBox(width: AppSpace.lg),
                    Expanded(child: Text(title, style: AppText.heading(26))),
                  ]),
                  const SizedBox(height: AppSpace.sm),
                  Padding(
                    padding: const EdgeInsets.only(left: 64),
                    child: Text('Rockketeyes · Thalamuxtech · $_updated',
                        style: AppText.label(12, color: AppColors.textFaint)),
                  ),
                  const SizedBox(height: AppSpace.xl),
                  GlassPanel(
                    padding: const EdgeInsets.all(AppSpace.xl),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        for (var i = 0; i < sections.length; i++) ...[
                          if (i > 0) const SizedBox(height: AppSpace.lg),
                          Text('${i + 1}. ${sections[i].title}', style: AppText.heading(17)),
                          const SizedBox(height: 6),
                          Text(sections[i].body, style: AppText.body(15, color: AppColors.textMuted)),
                        ],
                      ],
                    ),
                  ),
                  if (doc == LegalDoc.license) ...[
                    const SizedBox(height: AppSpace.lg),
                    Center(
                      child: TextButton(
                        // Open-source licenses require their notices to stay available.
                        onPressed: () => showLicensePage(context: context, applicationName: 'Rockketeyes'),
                        child: Text('Open-source notices', style: AppText.label(13, color: AppColors.textFaint)),
                      ),
                    ),
                  ],
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
